name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system deps & Buildozer/Cython
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            openjdk-11-jdk \
            ant \
            git zip unzip \
            zlib1g-dev libncurses5-dev libffi-dev liblzma-dev \
            build-essential wget
          pip3 install --upgrade buildozer cython

      - name: Build with Buildozer (full debug output)
        run: |
          # Use the system Ant installation
          export ANT_HOME=/usr/share/ant
          export PATH=$ANT_HOME/bin:$PATH

          # Run Buildozer at max verbosity to expose any errors
          buildozer --verbose --log-level=2 android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: qrlogger-apk
          path: bin/*.apk
